# .air.toml
root = "."
tmp_dir = "tmp"
[build]
  cmd = "./generate_docs.sh"
  bin = "./tmp/main"
  full_bin = "./tmp/main"
  exclude_dir = ["vendor", "tmp"]
  include_ext = ["go", "tpl", "tmpl", "html"]
  follow_symlink = true
  kill_delay = 1
  send_interrupt = true
[log]
  level = "debug"
  color = true
  timestamp = true
[web]
  addr = "localhost:9090"
  open_url = true
  url = "http://localhost:9090"
